// Bend Fly Shop
// EnvelopeBarcodeScanner.swift — VisionKit-based scanner sheet for sample-envelope barcodes.
//
// Presented from the researcher chat flow at the .envelopeScan step. Recognizes
// QR codes and Data Matrix symbols. Envelopes generated by us follow the
// "SMP:<id>" convention — that prefix is stripped before the value is returned.
// Anything else is returned as the raw scanned string so a researcher can still
// scan a legacy or third-party label and have the chat flow fall back gracefully.
//
// The user can also tap "Type instead" to dismiss the sheet and use the chat
// input bar to enter the ID manually (the canonical fallback for damaged or
// missing barcodes).

import SwiftUI
import Vision
import VisionKit
import AVFoundation

struct EnvelopeBarcodeScanner: View {
  /// Called with the parsed envelope ID (prefix stripped) when a scan succeeds.
  let onScan: (String) -> Void
  /// Called when the user taps "Type instead" — caller should dismiss the
  /// sheet so the chat input bar regains focus.
  let onManualEntry: () -> Void
  /// Called when the user cancels without scanning.
  let onCancel: () -> Void

  @State private var statusText: String = "Hold the envelope barcode in the frame."
  @State private var statusIsError: Bool = false

  /// Strip the recognized "SMP:" prefix and return the bare ID. Falls back to
  /// the raw string for any other payload so the flow handles unknown formats
  /// gracefully (the researcher can still scan and the ID lands in the field).
  static func parsePayload(_ raw: String) -> String {
    let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
    let prefix = "SMP:"
    if trimmed.uppercased().hasPrefix(prefix) {
      return String(trimmed.dropFirst(prefix.count)).trimmingCharacters(in: .whitespaces)
    }
    return trimmed
  }

  var body: some View {
    ZStack(alignment: .bottom) {
      Color.brandBackground.ignoresSafeArea()

      scannerArea
        .ignoresSafeArea()

      VStack(spacing: 12) {
        Spacer()

        Text(statusText)
          .font(.brandSubheadline.weight(.medium))
          .foregroundColor(statusIsError ? .red : .white)
          .multilineTextAlignment(.center)
          .padding(.horizontal, 24)
          .padding(.vertical, 10)
          .background(.black.opacity(0.55), in: Capsule())
          .padding(.horizontal, 24)

        HStack(spacing: 12) {
          Button(action: onManualEntry) {
            Label("Type instead", systemImage: "keyboard")
              .font(.brandSubheadline.weight(.semibold))
              .frame(maxWidth: .infinity)
              .padding(.vertical, 12)
              .foregroundColor(.brandTextPrimary)
              .background(Color.brandTextPrimary.opacity(0.18), in: RoundedRectangle(cornerRadius: 10))
          }

          Button(action: onCancel) {
            Text("Cancel")
              .font(.brandSubheadline.weight(.semibold))
              .frame(maxWidth: .infinity)
              .padding(.vertical, 12)
              .foregroundColor(.brandTextPrimary)
              .background(Color.brandStroke, in: RoundedRectangle(cornerRadius: 10))
          }
        }
        .padding(.horizontal, 24)
        .padding(.bottom, 28)
      }
    }
  }

  @ViewBuilder
  private var scannerArea: some View {
    if DataScannerViewController.isSupported && DataScannerViewController.isAvailable {
      DataScannerRepresentable(
        onScan: handleScan,
        onError: { message in
          statusText = message
          statusIsError = true
        }
      )
    } else {
      // Simulator (no rear camera) or unsupported device — surface an
      // explanation and steer the user to manual entry.
      VStack(spacing: 12) {
        Image(systemName: "barcode.viewfinder")
          .font(.system(size: 64))
          .foregroundColor(.brandTextPrimary.opacity(0.7))
        Text("Camera scanning is unavailable on this device.")
          .font(.brandHeadline)
          .foregroundColor(.brandTextPrimary)
          .multilineTextAlignment(.center)
        Text("Tap \"Type instead\" to enter the envelope ID manually.")
          .font(.brandSubheadline)
          .foregroundColor(.brandTextPrimary.opacity(0.7))
          .multilineTextAlignment(.center)
      }
      .padding(32)
    }
  }

  private func handleScan(_ raw: String) {
    let id = Self.parsePayload(raw)
    guard !id.isEmpty else {
      statusText = "Couldn't read that barcode — try again."
      statusIsError = true
      return
    }
    onScan(id)
  }
}

// MARK: - DataScannerViewController bridge

private struct DataScannerRepresentable: UIViewControllerRepresentable {
  let onScan: (String) -> Void
  let onError: (String) -> Void

  func makeCoordinator() -> Coordinator {
    Coordinator(onScan: onScan, onError: onError)
  }

  func makeUIViewController(context: Context) -> DataScannerViewController {
    let controller = DataScannerViewController(
      recognizedDataTypes: [.barcode(symbologies: [.qr, .dataMatrix])],
      qualityLevel: .balanced,
      recognizesMultipleItems: false,
      isHighFrameRateTrackingEnabled: false,
      isPinchToZoomEnabled: true,
      isGuidanceEnabled: true,
      isHighlightingEnabled: true
    )
    controller.delegate = context.coordinator
    return controller
  }

  func updateUIViewController(_ controller: DataScannerViewController, context: Context) {
    // Start scanning lazily — the controller throws if started before being on
    // screen, so we wrap in a Task to defer until the next runloop tick.
    Task { @MainActor in
      do {
        try controller.startScanning()
      } catch {
        onError("Couldn't start the scanner: \(error.localizedDescription)")
      }
    }
  }

  static func dismantleUIViewController(_ controller: DataScannerViewController, coordinator: Coordinator) {
    controller.stopScanning()
  }

  final class Coordinator: NSObject, DataScannerViewControllerDelegate {
    let onScan: (String) -> Void
    let onError: (String) -> Void
    /// Guard so a single scan doesn't fire onScan multiple times if VisionKit
    /// reports the same item across consecutive frames before the sheet dismisses.
    private var didReportScan = false

    init(onScan: @escaping (String) -> Void, onError: @escaping (String) -> Void) {
      self.onScan = onScan
      self.onError = onError
    }

    func dataScanner(_ dataScanner: DataScannerViewController, didAdd addedItems: [RecognizedItem], allItems: [RecognizedItem]) {
      report(addedItems)
    }

    func dataScanner(_ dataScanner: DataScannerViewController, didTapOn item: RecognizedItem) {
      report([item])
    }

    func dataScanner(_ dataScanner: DataScannerViewController, becameUnavailableWithError error: DataScannerViewController.ScanningUnavailable) {
      onError("Scanner unavailable: \(error.localizedDescription)")
    }

    private func report(_ items: [RecognizedItem]) {
      guard !didReportScan else { return }
      for item in items {
        if case let .barcode(barcode) = item, let payload = barcode.payloadStringValue, !payload.isEmpty {
          didReportScan = true
          onScan(payload)
          return
        }
      }
    }
  }
}
